kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: %NAME%
    app: java
  name: %NAME%
  namespace: java
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: %NAME%
  template:
    metadata:
      labels:
        k8s-app: %NAME%
        app: java
    spec:
      volumes:
      - name: zingmm0
        hostPath:
          path: /dev/zing_mm0    
      containers:
        - name: %NAME%
          resources:
            limits:
              memory: %MEM_LIMIT%
          image: %IMAGE%
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME", "SYS_RAWIO", "SYS_ADMIN", "ALL"]
          env:
          - name: _JAVA_OPTIONS
            value: %JAVA_OPTS%
          command: ["/bin/bash", "-c", "curl -L https://github.com/jelastic/java-vertical-scaling-test/raw/master/dist/app.jar --output app.jar && sleep 3 && %CMD%"]
      nodeSelector:
        opts: %NODE%
