kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: java-openj9
    app: java
  name: java-openj9
  namespace: java
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: java-openj9
  template:
    metadata:
      labels:
        k8s-app: java-openj9
        app: java
    spec:
      containers:
        - name: java-openj9
          resources:
            limits:
              memory: %MEM_LIMIT%
          image: jelastic/javaengine:openj9-0.15.1-12.0.2
          imagePullPolicy: Always
          env:
          - name: OPENJ9_JAVA_OPTIONS
            value: %JAVA_OPTS%
          command: ["/bin/bash", "-c", "curl -L https://github.com/jelastic/java-vertical-scaling-test/raw/master/dist/app.jar --output app.jar && sleep 3 && %CMD%"]
      nodeSelector:
        gc: OpenJ9
