kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: java-zulujdk
    app: java
  name: java-zulujdk
  namespace: java
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: java-zulujdk
  template:
    metadata:
      labels:
        k8s-app: java-zulujdk
        app: java
    spec:
      containers:
        - name: java-zulujdk
          image: jelastic/javaengine:zulujdk-12.0.2
          imagePullPolicy: Always
          resources:
            limits:
              memory: %MEM_LIMIT%
          env:
          - name: JAVA_OPTS
            value: %JAVA_OPTS%
          command: ["/bin/bash", "-c", "curl -L https://github.com/jelastic/java-vertical-scaling-test/raw/master/dist/app.jar --output app.jar && sleep 3 && %CMD%"]
      nodeSelector:
        java: zulujdk
