type: update
description: |
    Java vertical scaling test on Kubernetes: G1 @ Dragonwell 8.1.1

    **Important!** Apply this Add-On to a Kubernetes Cluster with **4** worker nodes.
    Each pod is deployed to its dedicated labeled node to easily track memory utilization.


name: Java Vertical Scaling on Kubernetes
logo: https://github.com/jelastic/java-vertical-scaling-test/raw/master/kubernetes/images/kube.png
baseUrl: https://raw.githubusercontent.com/jelastic/java-vertical-scaling-test/master/kubernetes

globals:
  # keep \\\\n for sed replacement!!!
  name: dragonwell
  image: devbeta/javaengine:dragonwell-8.1.1
  cmd: java --uninstall; echo -ne '\\\\n' | java -jar app.jar 100 2
  limit: 3Gi
  cloudlets: 40
  common: -Xmx3g -Xms3g -XX:+UseCompressedOops -XX:+UseG1GC
  container1: custom1
  container2: custom2
  container3: custom3
  container4: default
  opts-container1: -XX:+G1ElasticHeap -XX:+ElasticHeapPeriodicUncommit -XX:ElasticHeapPeriodicYGCIntervalMillis=10000 -XX:ElasticHeapYGCIntervalMinMillis=1000 -XX:ElasticHeapInitialMarkIntervalMinMillis=1000 -XX:ElasticHeapPeriodicInitialMarkIntervalMillis=600000 -XX:ElasticHeapPeriodicUncommitStartupDelay=1 -XX:ElasticHeapPeriodicMinYoungCommitPercent=10 -XX:ElasticHeapPeriodicUncommitStartupDelay=10 -XX:ElasticHeapPeriodicMinYoungCommitPercent=10 -XX:ElasticHeapMinYoungCommitPercent=5
  opts-container2: -XX:+G1ElasticHeap -XX:+ElasticHeapPeriodicUncommit -XX:ElasticHeapPeriodicYGCIntervalMillis=30000 -XX:ElasticHeapYGCIntervalMinMillis=1000 -XX:ElasticHeapInitialMarkIntervalMinMillis=1000 -XX:ElasticHeapPeriodicInitialMarkIntervalMillis=300000 -XX:ElasticHeapPeriodicUncommitStartupDelay=1 -XX:ElasticHeapPeriodicMinYoungCommitPercent=10 -XX:ElasticHeapPeriodicUncommitStartupDelay=10 -XX:ElasticHeapPeriodicMinYoungCommitPercent=30 -XX:ElasticHeapMinYoungCommitPercent=10
  opts-container3: -XX:+G1ElasticHeap -XX:+ElasticHeapPeriodicUncommit -XX:ElasticHeapPeriodicYGCIntervalMillis=10000 -XX:ElasticHeapYGCIntervalMinMillis=1000 -XX:ElasticHeapInitialMarkIntervalMinMillis=1000 -XX:ElasticHeapPeriodicInitialMarkIntervalMillis=60000 -XX:ElasticHeapPeriodicUncommitStartupDelay=1 -XX:ElasticHeapPeriodicMinYoungCommitPercent=10 -XX:ElasticHeapPeriodicUncommitStartupDelay=10 -XX:ElasticHeapPeriodicMinYoungCommitPercent=10 -XX:ElasticHeapMinYoungCommitPercent=5
  opts-container4: -XX:+G1ElasticHeap -XX:+ElasticHeapPeriodicUncommit
  
mixins:
 - manifests/actions.jps

onInstall:
   - labelNodes
   - renameNodes
   - setCloudlets
   - deploy
   - monit
success: ${globals.success}
