type: update
description: |
    Java vertical scaling test on Kubernetes: OpenJ9

    **Important!** Apply this Add-On to a Kubernetes Cluster with **4** worker nodes.
    Each pod is deployed to its dedicated labeled node to easily track memory utilization.


name: Java Vertical Scaling on Kubernetes
logo: https://github.com/jelastic/java-vertical-scaling-test/raw/master/kubernetes/images/kube.png
baseUrl: https://raw.githubusercontent.com/jelastic/java-vertical-scaling-test/master/kubernetes

globals:
  # keep \\\\n for sed replacement!!!
  name: openj9
  image: jelastic/javaengine:openj9-0.15.1-12.0.2
  cmd: java --uninstall; echo -ne '\\\\n' | java -jar app.jar 100 2
  limit: 3Gi
  cloudlets: 40
  common: -Xmx3g -Xms32m -XX:+UseCompressedOops
  container1: option1
  container2: option2
  container3: option3
  container4: option4
  opts-container1: -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle -XX:IdleTuningMinIdleWaitTime=1 -Xjit:waitTimeToEnterDeepIdleMode=1000
  opts-container2: -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle -XX:IdleTuningMinIdleWaitTime=1 -Xjit:waitTimeToEnterDeepIdleMode=1000
  opts-container3: -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle -XX:IdleTuningMinIdleWaitTime=1 -Xjit:waitTimeToEnterDeepIdleMode=1000
  opts-container4: -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle -XX:IdleTuningMinIdleWaitTime=1 -Xjit:waitTimeToEnterDeepIdleMode=1000

mixins:
 - manifests/actions.jps

onInstall:
   - labelNodes
   - renameNodes
   - setCloudlets
   - deploy
   - monit
success: ${globals.success}
