type: update
description: |
    Java vertical scaling test on Kubernetes: ZGC @ Oracle OpenJDK

    **Important!** Apply this Add-On to a Kubernetes Cluster with **4** worker nodes.
    Each pod is deployed to its dedicated labeled node to easily track memory utilization.


name: Java Vertical Scaling on Kubernetes
logo: https://github.com/jelastic/java-vertical-scaling-test/raw/master/kubernetes/images/kube.png
baseUrl: https://raw.githubusercontent.com/jelastic/java-vertical-scaling-test/master/kubernetes

globals:
  # keep \\\\n for sed replacement!!!
  name: zgc
  image: jelastic/javaengine:openjdk-13.ea-b31
  cmd: java --uninstall; echo -ne '\\\\n' | java -jar app.jar 100 2
  limit: 3Gi
  cloudlets: 40
  common: -Xmx3g -Xms32m -XX:+UseCompressedOops -XX:+UnlockExperimentalVMOptions -XX:+UseZGC
  container1: delay1-int30
  container2: delay30-int60
  container3: delay60-int30
  container4: delay30-int1
  opts-container1: -XX:ZUncommitDelay=1 -XX:ZCollectionInterval=30
  opts-container2: -XX:ZUncommitDelay=30 -XX:ZCollectionInterval=60
  opts-container3: -XX:ZUncommitDelay=60 -XX:ZCollectionInterval=30
  opts-container4: -XX:ZUncommitDelay=30 -XX:ZCollectionInterval=1

mixins:
 - manifests/actions.jps

onInstall:
   - labelNodes
   - renameNodes
   - setCloudlets
   - deploy
   - monit
success: ${globals.success}
